apiVersion: v1
kind: Pod
metadata:
  name: secret-test
spec:
  containers:
  - name: secret-test
    image: busybox
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: app-secret
