apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-test
spec:
  containers:
  - name: secret-volume-test
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true

  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
